---
abstract: 'fetch, build and use the Bootstrap CSS Framework'
author:
  - 'Thomas Berger <perl@lokis-chaos.de>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Bootstrap
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Zip: '0'
  CSS::LESS::Filter: '0'
  HTTP::Tiny: '0'
  Path::Extended: '0'
  perl: '5.006'
version: '0.02'
